packages:
  - "."
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@deepseek-ai/cordis-plugin-loader@1.0.5'
  - '@deepseek-ai/cordis@4.0.4'
  - '@deepseek-ai/cosmokit@1.8.5'
  - '@deepseek-ai/dsh-atomic-write@0.1.7-rc.1'
  - '@deepseek-ai/dsh-brand@0.1.7-rc.1'
  - '@deepseek-ai/dsh-client-connection@0.1.7-rc.1'
  - '@deepseek-ai/dsh-client-locale@0.1.7-rc.1'
  - '@deepseek-ai/dsh-client-ui-renderer@0.1.7-rc.1'
  - '@deepseek-ai/dsh-client-ui-session@0.1.7-rc.1'
  - '@deepseek-ai/dsh-client-ui-settings@0.1.7-rc.1'
  - '@deepseek-ai/dsh-client-ui-sidebar@0.1.7-rc.1'
  - '@deepseek-ai/dsh-client-ui-slots@0.1.7-rc.1'
  - '@deepseek-ai/dsh-config-editor@0.1.7-rc.1'
  - '@deepseek-ai/dsh-credentials@0.1.7-rc.1'
  - '@deepseek-ai/dsh-settings@0.1.7-rc.1'
  - '@deepseek-ai/dsh-util-values@0.1.7-rc.1'
  - '@deepseek-ai/schemastery@3.18.4'
overrides:
  "@deepseek-ai/cordis": "4.0.4"
  "@deepseek-ai/schemastery": "3.18.4"
